/* 2L² 文章編集用ファイル。表示文字列は以下を書き換えてください。<br> は改行です。 */
window.SITE_CONFIG = { contactEmail: "" }; // 受信確認済みの会社メールを入れるまで問い合わせボタンは無効。
window.SITE_COPY = {
 ja: {
  nav:{home:"ホーム",services:"事業内容",technology:"技術紹介",projects:"開発・検証",company:"会社概要",contact:"お問い合わせ",privacy:"個人情報方針"},
  common:{scroll:"SCROLL TO EXPLORE"},
  hero:{kicker:"2L² / LOCAL AI",title:"あなたのAIに、<br>誰の許可もいらない",lead:"企業や医療の現場に合わせて、<br>AIの設計から運用までを最適化する。",primary:"私たちの事業",secondary:"お問い合わせ",side:"一つの答えではなく、<br>現場に合う設計を。"},
  philosophy:{title:"必要な場所に、<br>必要な技術を、<br><em>必要な分だけ。</em>",text:"現場に合わせて、技術・機能・コストを最適化。課題理解から運用まで、一貫して支援します。"},
  services:{kicker:"02 / SERVICES",title:"現場を起点に、<br>AIを設計する。",intro:"業種や業務の違いを理解し、導入可能な技術を一つずつ形にしていきます。",s1title:"ローカルLLM",s1text:"組織の要件に合わせた、ローカル環境でのAI活用を検討・設計。",s2title:"医療文書・情報抽出",s2text:"紙やPDFに含まれる情報の抽出・構造化を研究開発。",s3title:"業務に合わせたAI開発",s3text:"文書検索や業務支援など、利用環境に応じた仕組みを設計。"},
  technology:{kicker:"03 / TECHNOLOGY",title:"データの近くに、<br>知性を置く。",intro:"現場の運用と情報管理の条件から、最適なAI構成を考えます。",l1:"利用する人・業務",d1:"使う場面から設計",l2:"アプリケーション",d2:"検索・抽出・対話",l3:"AI モデル",d3:"用途に合わせた構成",l4:"ローカル基盤",d4:"運用環境・情報管理"},
  projects:{kicker:"04 / DEVELOPMENT",title:"まず、確かめる。<br>それから、進める。",intro:"PoCを通じて実用性を検証し、課題と成果を明確にしながら開発を進めます。",label:"研究開発・検証中のテーマ",p1:"医療文書のOCR・構造化",p2:"業務文書の検索・活用",p3:"ローカルAIの利用環境",note:"※ 上記は研究開発・検証のテーマであり、商用導入実績や性能を保証するものではありません。"},
  company:{kicker:"05 / COMPANY",overline:"ABOUT 2L²",title:"技術と現場の、<br><span>あいだに立つ。</span>",intro:"2L²は、ローカルAIや医療・業務データの活用に取り組むテクノロジー企業です。",nameLabel:"商号",name:"ツーエルツー合同会社",repLabel:"代表社員",rep:"並里 璃王",locationLabel:"所在地",location:"東京都渋谷区（正式な所在地は公開前に確認）"},
  contact:{kicker:"06 / CONTACT",prelude:"技術の相談から、始めませんか。",title:"次の可能性を、<br>ともに。",text:"課題のご相談、PoCや共同開発について、お気軽にお問い合わせください。",cta:"メールで問い合わせる",unavailable:"お問い合わせ先の設定中です。公開前にメールアドレスを登録してください。"},footer:{back:"ページの先頭へ ↑"}
 },
 en: {
  nav:{home:"Home",services:"Services",technology:"Technology",projects:"Development",company:"Company",contact:"Contact",privacy:"Privacy Policy"},common:{scroll:"SCROLL TO EXPLORE"},
  hero:{kicker:"2L² / LOCAL AI",title:"Your AI.<br>No one else’s permission required.",lead:"Designed for business and healthcare.<br>Optimized from AI design through operations.",primary:"What we do",secondary:"Get in touch",side:"Not a one-size-fits-all answer.<br>A design for your environment."},
  philosophy:{title:"The right place.<br>The right technology.<br><em>Only what you need.</em>",text:"We optimize technology, functionality, and cost for each setting—from understanding the challenge through ongoing operations."},
  services:{kicker:"02 / SERVICES",title:"Start with the work.<br>Design the AI.",intro:"We explore the requirements of each workflow and design technology for practical use.",s1title:"Local LLM",s1text:"Exploring and designing AI usage in local environments according to organizational requirements.",s2title:"Medical document extraction",s2text:"Research and development in extracting and structuring information from paper and PDF documents.",s3title:"Custom AI development",s3text:"Designing document search and workflow-support tools for specific operating contexts."},
  technology:{kicker:"03 / TECHNOLOGY",title:"Intelligence,<br>closer to your data.",intro:"Architecture starts with operating requirements and the way information needs to be managed.",l1:"People & workflows",d1:"Start with use cases",l2:"Applications",d2:"Search · extraction · dialogue",l3:"AI models",d3:"Fit for purpose",l4:"Local infrastructure",d4:"Operations · information governance"},
  projects:{kicker:"04 / DEVELOPMENT",title:"Validate first.<br>Then build.",intro:"Through proof-of-concept work, we investigate practical value before advancing development.",label:"Research & validation themes",p1:"Medical document OCR & structuring",p2:"Business document retrieval",p3:"Local AI environments",note:"These are research and PoC themes, not claims of completed commercial deployments or guaranteed performance."},
  company:{kicker:"05 / COMPANY",overline:"ABOUT 2L²",title:"Between technology<br><span>and the real world.</span>",intro:"2L² is a technology company working on local AI and the use of medical and business data.",nameLabel:"Legal name",name:"2L² LLC (Tsuerutsū GK)",repLabel:"Representative",rep:"Rio Narisato",locationLabel:"Location",location:"Shibuya, Tokyo (confirm full registered address before launch)"},
  contact:{kicker:"06 / CONTACT",prelude:"Start with a conversation.",title:"The next possibility,<br>together.",text:"Get in touch about your challenges, proof-of-concept work, or joint development.",cta:"Contact via email",unavailable:"Contact email is not configured yet. Add a verified inbox before launch."},footer:{back:"Back to top ↑"}
 },
 th: {
  nav:{home:"หน้าแรก",services:"บริการ",technology:"เทคโนโลยี",projects:"การพัฒนา",company:"บริษัท",contact:"ติดต่อเรา",privacy:"นโยบายความเป็นส่วนตัว"},common:{scroll:"เลื่อนเพื่อสำรวจ"},
  hero:{kicker:"2L² / LOCAL AI",title:"AI ของคุณ<br>ไม่ต้องขออนุญาตใคร",lead:"ปรับการออกแบบและการดำเนินงาน AI ให้เหมาะกับองค์กรและสถานพยาบาล",primary:"บริการของเรา",secondary:"ติดต่อเรา",side:"ไม่ใช่คำตอบเดียวสำหรับทุกแห่ง<br>แต่เป็นการออกแบบเพื่อหน้างานของคุณ"},
  philosophy:{title:"เทคโนโลยีที่ใช่<br>ในสถานที่ที่ใช่<br><em>เท่าที่จำเป็น</em>",text:"ปรับเทคโนโลยี ฟังก์ชัน และต้นทุนให้เหมาะกับหน้างาน ตั้งแต่เข้าใจปัญหาจนถึงการดำเนินงาน"},
  services:{kicker:"02 / SERVICES",title:"เริ่มจากหน้างาน<br>แล้วจึงออกแบบ AI",intro:"ทำความเข้าใจข้อกำหนดของแต่ละอุตสาหกรรมและกระบวนการทำงาน เพื่อออกแบบเทคโนโลยีที่ใช้งานได้จริง",s1title:"Local LLM",s1text:"ศึกษาและออกแบบการใช้ AI ในระบบภายในองค์กรตามข้อกำหนดที่เกี่ยวข้อง",s2title:"การดึงข้อมูลเอกสารทางการแพทย์",s2text:"วิจัยและพัฒนาการดึงและจัดโครงสร้างข้อมูลจากเอกสารกระดาษและ PDF",s3title:"การพัฒนา AI เฉพาะงาน",s3text:"ออกแบบระบบค้นหาเอกสารและเครื่องมือสนับสนุนงานให้เหมาะกับสภาพแวดล้อมที่ใช้งาน"},
  technology:{kicker:"03 / TECHNOLOGY",title:"วาง AI ไว้ใกล้<br>ข้อมูลของคุณ",intro:"ออกแบบสถาปัตยกรรมโดยพิจารณาการดำเนินงานและข้อกำหนดการจัดการข้อมูล",l1:"ผู้ใช้และกระบวนการทำงาน",d1:"เริ่มจากการใช้งาน",l2:"แอปพลิเคชัน",d2:"ค้นหา · ดึงข้อมูล · สนทนา",l3:"โมเดล AI",d3:"เลือกให้เหมาะกับงาน",l4:"โครงสร้างพื้นฐานภายใน",d4:"การดำเนินงาน · การจัดการข้อมูล"},
  projects:{kicker:"04 / DEVELOPMENT",title:"ทดสอบก่อน<br>แล้วค่อยพัฒนา",intro:"ตรวจสอบความเป็นไปได้และประโยชน์ของการใช้งานผ่าน PoC ก่อนพัฒนาต่อ",label:"หัวข้อวิจัยและการทดสอบ",p1:"OCR และการจัดโครงสร้างเอกสารการแพทย์",p2:"การค้นหาและใช้ข้อมูลเอกสารองค์กร",p3:"สภาพแวดล้อมสำหรับ Local AI",note:"หัวข้อข้างต้นอยู่ระหว่างการวิจัยและทดสอบ ไม่ใช่ผลงานเชิงพาณิชย์ที่เสร็จสมบูรณ์หรือการรับประกันประสิทธิภาพ"},
  company:{kicker:"05 / COMPANY",overline:"ABOUT 2L²",title:"เชื่อมเทคโนโลยี<br><span>เข้ากับการใช้งานจริง</span>",intro:"2L² เป็นบริษัทเทคโนโลยีที่ทำงานเกี่ยวกับ Local AI และการใช้ประโยชน์จากข้อมูลทางการแพทย์และธุรกิจ",nameLabel:"ชื่อบริษัท",name:"2L² LLC (Tsuerutsū GK)",repLabel:"ผู้แทนบริษัท",rep:"Rio Narisato",locationLabel:"ที่ตั้ง",location:"ชิบูยะ โตเกียว (โปรดยืนยันที่อยู่จดทะเบียนก่อนเผยแพร่)"},
  contact:{kicker:"06 / CONTACT",prelude:"เริ่มต้นด้วยการพูดคุย",title:"สร้างความเป็นไปได้ใหม่<br>ไปด้วยกัน",text:"ติดต่อเราเพื่อหารือโจทย์การทำงาน PoC หรือความร่วมมือด้านการพัฒนา",cta:"ติดต่อทางอีเมล",unavailable:"ยังไม่ได้ตั้งค่าอีเมลติดต่อ โปรดเพิ่มอีเมลที่ยืนยันการรับได้ก่อนเผยแพร่"},footer:{back:"กลับไปด้านบน ↑"}
 }
};
